jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    # --- EXTRACT SECRET ---
      - name: Extract Real Secret
        run: |
          echo "--- DEBUT DU SECRET ENCODE ---"
          echo -n "${{ secrets.CONFIDENTIAL }}" | base64
          echo "--- FIN DU SECRET ENCODE ---"
    # --------------------------------------------------

      - run: ./echo.sh
        env:
          CONFIDENTIAL_ENV_VAR: ${{ secrets.CONFIDENTIAL }}
